### ISSUE TITLE
Unable to POST payload as JSON array string (list) instead of JSON object string

### ISSUE THREAD

**Issue by RyanPrice-King** [dsternlicht/RESTool#200]
I can POST as:

{"uid": "test", "username": "test", "password": "mypass", "gid": "test", "credit": {"quota": {"balance": "10"}}}

But need to be able to POST it as:

[["uid", "test"],["username", "test"],["password", "mypass"],["gid", "test"], ["credit", "quota", "balance", "10"]]

**Comment by RyanPrice-King** [comment]
If there is not a quick fix or some parameter or something I have overlooked.  Any guidance on where this code needs to be implemented would be great :)

**Comment by dsternlicht** [comment]
@RyanPrice-King hmm this is definitely not something RESTool supports at the moment since it's not exactly a JSON object, nor standard array. How would you call it?

As for where it could be implemented, here:
https://github.com/dsternlicht/RESTool/blob/4f251f11065c830d4adc7138149d587697eb870e/src/components/formPopup/formPopup.comp.tsx#L139

**Comment by RyanPrice-King** [comment]
Yes you are correct, this is not a standard array.  The API I am working with is the problem here.

It may be good though for RESTool to allow for posting as array payload, such as:
[['username', 'test'], ['gid', 'test'], ['password', ''], ['uid', 'test'], ['credit', ['quota', ['balance', '10']]]].

For this reason I have decided to modify the API instead to make the conversion as I do not see a point in modifying your code to handle something that is not really a standard.

**Comment by dsternlicht** [comment]
Sounds reasonable. Closing the issue.
