### ISSUE TITLE
Multiselect

### ISSUE THREAD

**Issue by kordimsan** [dsternlicht/RESTool#237]
Hi

How works "multi" property:
I trying to do this:
`{
  "name": "categories",
  "label": "categories",
  "options": [
    "news",
    "sport",
    "tech",
    "world",
    "finance",
    "politics",
    "business"
  ],
  "type": "select",
  "multi": true
},`
and the select dropdown still do not allow multi selection

**Comment by dsternlicht** [comment]
@kordimsan hmm not sure why. This is exactly how you should use it.

**Comment by eimwe** [comment]
Hi @kordimsan and @dsternlicht  ! I don't know if this still relevant, but in order to make it work the type needs to be a 'select-multi': `"type": "select-multi"`, not plain 'select'. This plus `"multi": true` setting are making multiselect render as it should.

I took the liberty of creating a [pull request](https://github.com/dsternlicht/RESTool/pull/252) that updates README sections on multiselect usage.

**Comment by dsternlicht** [comment]
@eimwe nice catch! The PR has been approved.
